[package]
name = "mailcache"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
model.workspace = true
serde.workspace = true
anyhow.workspace = true
thiserror.workspace = true
mail-parser.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile.workspace = true
